<?xml version='1.0'?>
<robot xmlns:xacro='http://www.ros.org/wiki/xacro' >

    

    <!-- XACRO CONSTANTS  -->
    <xacro:property name="chassis_length" value="0.9"/>
    <xacro:property name="chassis_width" value="0.64"/>
    <xacro:property name="chassis_height" value="0.19"/>
    <xacro:property name="chassis_mass" value="70"/>

    <xacro:property name="traction_wheel_mass" value="1"/>
    <xacro:property name="traction_wheel_base" value="0.88"/>
    <xacro:property name="traction_max_wheel_torque" value="20000"/>
    <xacro:property name="traction_wheel_friction" value="5.0"/>
    <xacro:property name="trolley_wheel_width" value="0.05"/>


    <xacro:property name="trolley_wheel_mass" value="0.1"/>
    <xacro:property name="trolley_track_width" value="0.84"/>
    <xacro:property name="trolley_wheel_friction" value="0.0"/>
    <xacro:property name="trolley_wheel_radius" value="0.08"/>
    <!-- a small constant -->
    <xacro:property name="eps" value="0.002"/>

    <xacro:property name="traction_wheel_radius" value="0.1"/>
    <xacro:property name="traction_wheel_width" value="0.05"/>
    <xacro:property name="traction_track_width" value="0.6"/>

    <xacro:property name="two_d_lidar_update_rate" value="30"/>
    <xacro:property name="two_d_lidar_sample_size" value="361"/>
    <xacro:property name="two_d_lidar_min_angle" value="0"/>
    <xacro:property name="two_d_lidar_max_angle" value="360"/>
    <xacro:property name="two_d_lidar_min_range" value="0.55"/>
    <xacro:property name="two_d_lidar_max_range" value="16"/>

    <xacro:property name="camera_baseline" value="0.06"/>
    <xacro:property name="camera_height" value="0.10"/>
    <xacro:property name="camera_horizontal_fov" value="60"/>

    <xacro:arg name="robot_namespace" default=""/>
    <xacro:arg name="wheel_odom_topic" default="odom" />
    <xacro:arg name="camera_enabled" default="false" />
    <xacro:arg name="stereo_camera_enabled" default="false" />
    <xacro:arg name="two_d_lidar_enabled" default="false" />
    <xacro:arg name="publish_wheel_odom_tf" default="true" />
    <xacro:arg name="conveyor_enabled" default="false"/>
    <xacro:arg name="ground_truth_frame" default="map"/>
    <xacro:arg name="sim_gazebo" default="false" />
    <xacro:arg name="sim_gz" default="false" />
    <xacro:arg name="odometry_source" default="world" />

    <xacro:property name="odometry_source" value="$(arg odometry_source)"/>



    <!-- LOAD MACROS -->

    <xacro:include filename="macros.xacro"/>

    
    <xacro:include filename="gz.xacro"/>




    <!-- BASE LINK-->

    <link name="base_footprint"/>

    <link name="base_link"/>

    

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>




    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.45 0 0" rpy="0 0 0.0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="white">
                <color rgba="1.0 1.0 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertia mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z = "${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:box_inertia>
    </link>


    <joint name="middle_wheel_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="middle_wheel_left_visual"/>
        <origin xyz="0 ${traction_track_width/2} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>

    <link name="middle_wheel_left_visual">
        <visual>
             <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            
            <geometry>
                <cylinder radius="${traction_wheel_radius}" length="${traction_wheel_width}"/>
            </geometry>
            <self_collide>false</self_collide>
            <material name="plastic">
                <color rgba="0.1 0.1 0.1 1"/>
            </material>
        </visual>
        <collision>
             <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${traction_wheel_radius}" length="${traction_wheel_width}"/>
            </geometry>
            <self_collide>false</self_collide>
        </collision>
        <xacro:inertial_cylinder mass="${traction_wheel_mass}" length="${traction_wheel_width}" radius="${traction_wheel_radius}">
             <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
        </xacro:inertial_cylinder>
        <mu>5.0</mu>

    </link>

    <joint name="middle_wheel_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="middle_wheel_right_visual"/>
        <origin xyz="0 -${traction_track_width/2} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>
    <link name="middle_wheel_right_visual">
        <visual>
             <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${traction_wheel_radius}" length="${traction_wheel_width}"/>
            </geometry>
            <material name="plastic">
                <color rgba="0.1 0.1 0.1 1"/>
            </material>
            <self_collide>false</self_collide>
        </visual>
        <collision>
             <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${traction_wheel_radius}" length="${traction_wheel_width}"/>
            </geometry>
            <self_collide>false</self_collide>
        </collision>
        <xacro:inertial_cylinder mass="${traction_wheel_mass}" length="${traction_wheel_width}" radius="${traction_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
        </xacro:inertial_cylinder>
        <mu>5.0</mu>

        <gazebo>
            <plugin filename="ignition-gazebo-joint-state-publisher-system" name="ignition::gazebo::systems::JointStatePublisher">
                <topic>/joint_states</topic>
                <joint_name>Middle_wheel_right_joint</joint_name>
            </plugin>
        </gazebo>
    </link>

    <transmission name="middle_wheel_left_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="middle_wheel_left_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="middle_wheel_left_motor">
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    </transmission>

    <transmission name="middle_wheel_right_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="middle_wheel_right_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="middle_wheel_right_motor">
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    </transmission>



    <!-- CASTER WHEELS -->



    <!-- Front Left Caster Wheel -->
    <joint name="front_left_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_left_caster_visual"/>
        <origin xyz="${chassis_length/2} 0.240 -0.02"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>
    <link name="front_left_caster_visual">

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
            <geometry>
                <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
            <geometry>
                <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${trolley_wheel_mass}" radius="${trolley_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
         <mu>0.0</mu>
    </link>


    <!-- Front Right Caster Wheel -->
    <joint name="front_right_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_right_caster_visual"/>
        <origin xyz="${chassis_length/2} -0.240 -0.02"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>
    <link name="front_right_caster_visual">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
            <geometry>
                <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>            
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                    <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${trolley_wheel_mass}" radius="${trolley_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
        <mu>0.0</mu>
    </link>


        <!-- back Left Caster Wheel -->
    <joint name="back_left_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="back_left_caster_visual"/>
        <origin xyz="-${chassis_length/2} 0.240 -0.02"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>
    <link name="back_left_caster_visual">

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
            <geometry>
                <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${trolley_wheel_mass}" radius="${trolley_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
         <mu>0.0</mu>
        
    </link>


    <!-- back Right Caster Wheel -->
    <joint name="back_right_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="back_right_caster_visual"/>
        <origin xyz="-${chassis_length/2} -0.240 -0.02"/>
        <axis xyz="0 1 0" rpy="0 0 0" />
    </joint>
    <link name="back_right_caster_visual">

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
            <geometry>
                <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                    <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${trolley_wheel_mass}" radius="${trolley_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
         <mu>0.0</mu>
        
    </link>

    


    <link name="two_d_lidar">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="0.06" radius="0.075"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="0.06" radius="0.075"/>
                </geometry>
             <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
            </visual>
            <xacro:inertial_cylinder mass="0.1" length="0.06" radius="0.075">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:inertial_cylinder>

    </link>

    <joint name="two_d_lidar_joint" type="fixed">
            <parent link="base_link"/>
            <child link="two_d_lidar"/>
            <origin xyz="0.0 0 0.08" rpy="0 0 0" />
    </joint>

        <gazebo reference="two_d_lidar">
            <material>Gazebo/White</material>
        </gazebo>

  

    <link name="imu_frame"/>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_frame"/>
        <origin xyz="0.0 0.0 0.08" rpy="0.0 0.0 0.0"/>
    </joint>



</robot>


