<?xml version='1.0'?>
<robot xmlns:xacro='http://www.ros.org/wiki/xacro' >

    <!-- XACRO CONSTANTS  -->
    <xacro:property name="chassis_length" value="0.9"/>
    <xacro:property name="chassis_width" value="0.64"/>
    <xacro:property name="chassis_height" value="0.19"/>
    <xacro:property name="chassis_mass" value="70"/>

    <xacro:property name="traction_wheel_mass" value="1"/>
    <xacro:property name="traction_wheel_base" value="0.88"/>
    <xacro:property name="traction_max_wheel_torque" value="20000"/>
    <xacro:property name="traction_wheel_friction" value="5.0"/>
    <xacro:property name="trolley_wheel_width" value="0.05"/>


    <xacro:property name="trolley_wheel_mass" value="0.1"/>
    <xacro:property name="trolley_track_width" value="0.74"/>
    <xacro:property name="trolley_wheel_friction" value="0.0"/>
    <xacro:property name="trolley_wheel_radius" value="0.05"/>
    <!-- a small constant -->
    <xacro:property name="eps" value="0.002"/>

    <xacro:property name="traction_wheel_radius" value="0.1"/>
    <xacro:property name="traction_wheel_width" value="0.05"/>
    <xacro:property name="traction_track_width" value="0.6"/>


        <!-- ............................... LOAD MACROS ................................. -->

    <xacro:include filename="macros.xacro"/>



    <!-- BASE LINK-->

    <link name="base_link">

    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.45 0 0" rpy="0 0 0.0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="aluminium">
                <color rgba="0.5 0.5 0.5 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${chassis_mass}" />
            <xacro:box_inertia m="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z = "${chassis_height}"/>
        </inertial>
    </link>

    <!-- MIDDLE WHEELS COLLISION AND VISUAL GEOMETRY -->
    <!--xacro:traction_wheel cardinality="middle" dexterity="left" origin_x="0" origin_y="${traction_track_width/2}" origin_z="-${chassis_height/2+2*trolley_wheel_radius+eps-traction_wheel_radius}"/-->
    <!--xacro:traction_wheel cardinality="middle" dexterity="right" origin_x="0" origin_y="-${traction_track_width/2}" origin_z="-${chassis_height/2+2*trolley_wheel_radius+eps-traction_wheel_radius}"/-->
       <joint name="middle_wheel_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="middle_wheel_left_visual"/>
        <!--origin xyz="0 ${traction_track_width/2} -${chassis_height/2+2*trolley_wheel_radius+eps-traction_wheel_radius}" rpy="-1.57 0 0"/-->
        <origin xyz="0 0.345 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    <link name="middle_wheel_left_visual">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            
            <geometry>
                <cylinder radius="${traction_wheel_radius}" length="${traction_wheel_width}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${traction_wheel_radius}" length="${traction_wheel_width}"/>
            </geometry>
        </collision>
    </link>

    <joint name="middle_wheel_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="middle_wheel_right_visual"/>
        <!--origin xyz="0 -${traction_track_width/2} -${chassis_height/2+2*trolley_wheel_radius+eps-traction_wheel_radius}" rpy="1.57 0 0"/-->
        <origin xyz="0 -0.345 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>
    <link name="middle_wheel_right_visual">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${traction_wheel_radius}" length="${traction_wheel_width}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${traction_wheel_radius}" length="${traction_wheel_width}"/>
            </geometry>
        </collision>
    </link>

    <!-- CASTER WHEELS -->
    <!-- Front Left Caster Wheel -->
    <joint name="front_left_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_left_caster_visual"/>
        <origin xyz="${chassis_length/2} ${trolley_track_width/2} -${trolley_wheel_radius+chassis_height/2}"/>
    </joint>
    <link name="front_left_caster_visual">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
        </collision>
    </link>
    <!-- Front Right Caster Wheel -->
    <joint name="front_right_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_right_caster_visual"/>
        <origin xyz="${chassis_length/2} -${trolley_track_width/2} -${trolley_wheel_radius+chassis_height/2}"/>
    </joint>
    <link name="front_right_caster_visual">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                    <sphere radius="${trolley_wheel_radius}"/>
            </geometry>
        </collision>
    </link>


</robot>


