name: Humble Build

on:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

jobs:
  humble_source:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-colcon-common-extensions

      - name: Create ROS 2 workspace
        run: |
          mkdir -p ros2_ws/src
          cp -r . ros2_ws/src/tars_amr_sim

      - name: Build the workspace
        run: |
          source /opt/ros/humble/setup.sh
          cd ros2_ws
          colcon build --event-handlers console_cohesion+



