name: Humble Build

on:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

jobs:
  humble_source:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble



      - name: Prepare ROS 2 workspace
        run: |
          mkdir -p ros2_ws/src/tars_amr_sim
          rsync -av --exclude='ros2_ws' . ros2_ws/src/tars_amr_sim
        shell: bash
        env:
          LANG: en_US.UTF-8



      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-colcon-common-extensions

      - name: Build the workspace
        run: |
          source /opt/ros/humble/setup.sh
          colcon build --event-handlers console_cohesion+


